{:ok, _} = Application.ensure_all_started(:ex_machina)
ExUnit.start()
Ecto.Adapters.SQL.Sandbox.mode(OPS.Repo, :manual)
Ecto.Adapters.SQL.Sandbox.mode(OPS.BlockRepo, :manual)
Ecto.Adapters.SQL.Sandbox.mode(OPS.EventManagerRepo, :manual)
